[tool]
[tool.poetry]
name = "BozQurd_Deployer"
version = "1.0"
description = "Automatic Deploy BozQurd to Heroku"
authors = ["aykhan026"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
